### register a new User
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Test",
  "password": "1234",
  "email": "dajdj@gmail.com",
  "profile_description": "Jovana stinkt!"
}

### Login User
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Test",
  "password": "1234"
}